struct songNode *createNode(char name[100], char artist[100]);
struct songNode* allocateSongs();
int whereInArray(char artist[100]);
void addSong(struct songNode *library[], struct songNode* song);
struct songNode *findSongByNameAndArtist(struct songNode *library[], char name[100], char artist[100]);
struct songNode *findSongByArtist(struct songNode *library[], char artist[100]);
void printSongListByAlphabet(struct songNode *library[], char letter);
void printSongByArtist(struct songNode *library[], char artist[100]);
void printLibrary(struct songNode *library[]);
void shuffle(struct songNode *library[], int count);
void deleteSong(struct songNode *library[], char name[100], char artist[100]);
void clearLibrary(struct songNode *library[]);